# permissions for end users to edit ingressoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressoperator-editor-role
rules:
- apiGroups:
  - solo.solo.com
  resources:
  - ingressoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solo.solo.com
  resources:
  - ingressoperators/status
  verbs:
  - get
